### ISSUE TITLE
Brilliant

### ISSUE THREAD

**Issue by Prathapkarumanchi** [ZanchiTheo/react-neucomponents#2]
Hi Zanchi, this is brilliant - excellent work on creating this library. 
I tried few other neumorphic libraries but this one is good and easy to work with.

I strongly suggest you to post some medium, dev.io articles to spread the word.
The documentation MD files can be converted/hosted as github pages.

----
Just-my-2-cents

**Comment by ZanchiTheo** [comment]
Hi Prathapkarumanchi, I really appreciate your message and I'm glad to see that you like the library !

Make a medium or dev.io article is a really cool idea, I already thought about that by didn't manage to find the time but I'm pretty sure I will write one when the library will be a little be more developed :)

In your message you talked about the documentation MD files. Which one are you talking about ? I hosted the library's documentation on GitHub using styleguidist for the frontend.

Thank you for your feedback, you rock ! ;)
