### ISSUE TITLE
Setting props

### ISSUE THREAD

**Issue by Prathapkarumanchi** [ZanchiTheo/react-neucomponents#3]
Hi @ZanchiTheo 

For all components, you should add style props to quickly fix minor things like padding and margins.

example: 
```
<NeuTextInput padding={20} margin={} />
<NeuTextInput paddingBottom={20} marginTop={15} />
```

**Comment by ZanchiTheo** [comment]
Hello again Prathapkarumanchi !

This a good idea, I'll try to make a quick fix as soon as I find some time. Meanwhile, you can use the style prop: `style={{ margin: "0 2rem 2rem 0" }}` if you want to quickly style the components. Stay tune, you rock ! ;)
